package snidgert.harrypottermod;

import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.EntityRegistry;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.client.Minecraft;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemStack;
import net.minecraft.potion.Potion;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.common.util.EnumHelper;
import snidgert.harrypottermod.armor.AurorArmorClass;
import snidgert.harrypottermod.armor.DeathEaterArmorClass;
import snidgert.harrypottermod.armor.InvisibilityCloakArmorClass;
import snidgert.harrypottermod.armor.WerewolfArmorClass;
import snidgert.harrypottermod.blocks.AcromantulaWebClass;
import snidgert.harrypottermod.blocks.BlackMarbleBrickClass;
import snidgert.harrypottermod.blocks.BlackMarbleClass;
import snidgert.harrypottermod.blocks.BoggartChestLockedClass;
import snidgert.harrypottermod.blocks.BoggartChestOpenClass;
import snidgert.harrypottermod.blocks.BrickClass;
import snidgert.harrypottermod.blocks.BrokenGlassClass;
import snidgert.harrypottermod.blocks.CabinetClass;
import snidgert.harrypottermod.blocks.CrystalballClass;
import snidgert.harrypottermod.blocks.CupClass;
import snidgert.harrypottermod.blocks.DarkMarkClass;
import snidgert.harrypottermod.blocks.DiademClass;
import snidgert.harrypottermod.blocks.DiaryClass;
import snidgert.harrypottermod.blocks.GOFClass;
import snidgert.harrypottermod.blocks.GlowstoneOffClass;
import snidgert.harrypottermod.blocks.GoldenEggClass;
import snidgert.harrypottermod.blocks.GoldenEggOpenClass;
import snidgert.harrypottermod.blocks.HandClass;
import snidgert.harrypottermod.blocks.HatClass;
import snidgert.harrypottermod.blocks.LampOffClass;
import snidgert.harrypottermod.blocks.LocketClass;
import snidgert.harrypottermod.blocks.MagicCauldronClass;
import snidgert.harrypottermod.blocks.MagicPowerOreClass;
import snidgert.harrypottermod.blocks.MarbleClass;
import snidgert.harrypottermod.blocks.MarblePillarClass;
import snidgert.harrypottermod.blocks.MirrorClass;
import snidgert.harrypottermod.blocks.PensieveClass;
import snidgert.harrypottermod.blocks.PensievePlaneClass;
import snidgert.harrypottermod.blocks.RingClass;
import snidgert.harrypottermod.blocks.RubyOreClass;
import snidgert.harrypottermod.blocks.SilverOreClass;
import snidgert.harrypottermod.blocks.SmoothBlackMarbleClass;
import snidgert.harrypottermod.blocks.SmoothMarbleClass;
import snidgert.harrypottermod.blocks.StoneSoldierBlockClass;
import snidgert.harrypottermod.blocks.StunClass;
import snidgert.harrypottermod.blocks.TorchOffClass;
import snidgert.harrypottermod.blocks.TriCupClass;
import snidgert.harrypottermod.blocks.WandCrafterClass;
import snidgert.harrypottermod.blocks.WingardiumLeviosaBlockClass;
import snidgert.harrypottermod.creativetabs.MagicFoodClass;
import snidgert.harrypottermod.creativetabs.MagicItemsClass;
import snidgert.harrypottermod.creativetabs.MagicMaterialsClass;
import snidgert.harrypottermod.creativetabs.SpellTabClass;
import snidgert.harrypottermod.creativetabs.WandCraftingClass;
import snidgert.harrypottermod.food.Bean10Class;
import snidgert.harrypottermod.food.Bean1Class;
import snidgert.harrypottermod.food.Bean2Class;
import snidgert.harrypottermod.food.Bean3Class;
import snidgert.harrypottermod.food.Bean4Class;
import snidgert.harrypottermod.food.Bean5Class;
import snidgert.harrypottermod.food.Bean6Class;
import snidgert.harrypottermod.food.Bean7Class;
import snidgert.harrypottermod.food.Bean8Class;
import snidgert.harrypottermod.food.Bean9Class;
import snidgert.harrypottermod.food.ButterBeerClass;
import snidgert.harrypottermod.food.ChocolateFrogClass;
import snidgert.harrypottermod.food.EveryFlavourBeansClass;
import snidgert.harrypottermod.food.GillyweedClass;
import snidgert.harrypottermod.food.NogtailCookedClass;
import snidgert.harrypottermod.food.NogtailRawClass;
import snidgert.harrypottermod.food.RamoraCookedClass;
import snidgert.harrypottermod.food.RamoraRawClass;
import snidgert.harrypottermod.food.TeboCookedClass;
import snidgert.harrypottermod.food.TeboRawClass;
import snidgert.harrypottermod.food.TileEntityEveryFlavourBeans;
import snidgert.harrypottermod.generation.WizardWorldGen;
import snidgert.harrypottermod.gui.GuiHandler;
import snidgert.harrypottermod.gui.SpellGUI;
import snidgert.harrypottermod.items.AugureyFeatherClass;
import snidgert.harrypottermod.items.BFangClass;
import snidgert.harrypottermod.items.BasiliskScaleClass;
import snidgert.harrypottermod.items.BatClass;
import snidgert.harrypottermod.items.BillywigStingerClass;
import snidgert.harrypottermod.items.BirchStickClass;
import snidgert.harrypottermod.items.BludgerClass;
import snidgert.harrypottermod.items.BoomslangVenomClass;
import snidgert.harrypottermod.items.BroomstickClass;
import snidgert.harrypottermod.items.ChimaeraScaleFragmentClass;
import snidgert.harrypottermod.items.DeluminatorClass;
import snidgert.harrypottermod.items.DemiguiseHairClass;
import snidgert.harrypottermod.items.DoxyWingClass;
import snidgert.harrypottermod.items.DragonHeartStringClass;
import snidgert.harrypottermod.items.ErumpentHideClass;
import snidgert.harrypottermod.items.FairyWingClass;
import snidgert.harrypottermod.items.FordAngliaClass;
import snidgert.harrypottermod.items.FwooperFeatherClass;
import snidgert.harrypottermod.items.GalleonClass;
import snidgert.harrypottermod.items.HippogriffFeatherClass;
import snidgert.harrypottermod.items.ItemStoreClass;
import snidgert.harrypottermod.items.KelpieHairClass;
import snidgert.harrypottermod.items.KeyClass;
import snidgert.harrypottermod.items.KnutClass;
import snidgert.harrypottermod.items.MagicBookClass;
import snidgert.harrypottermod.items.MagicPowerClass;
import snidgert.harrypottermod.items.MaraudersMapClass;
import snidgert.harrypottermod.items.MasterKeyClass;
import snidgert.harrypottermod.items.MirrorShardClass;
import snidgert.harrypottermod.items.MonsterBookClass;
import snidgert.harrypottermod.items.Motercycle2Class;
import snidgert.harrypottermod.items.MotercycleClass;
import snidgert.harrypottermod.items.OakStickClass;
import snidgert.harrypottermod.items.PStoneClass;
import snidgert.harrypottermod.items.PenknifeClass;
import snidgert.harrypottermod.items.PhoenixFeatherClass;
import snidgert.harrypottermod.items.PutOuterClass;
import snidgert.harrypottermod.items.QuaffleClass;
import snidgert.harrypottermod.items.RStoneClass;
import snidgert.harrypottermod.items.RemembrallClass;
import snidgert.harrypottermod.items.RowanStickClass;
import snidgert.harrypottermod.items.RubyClass;
import snidgert.harrypottermod.items.SickleClass;
import snidgert.harrypottermod.items.SilverIngotClass;
import snidgert.harrypottermod.items.SockClass;
import snidgert.harrypottermod.items.TheGoldenSnitchClass;
import snidgert.harrypottermod.items.TimeTurnerClass;
import snidgert.harrypottermod.items.TridentClass;
import snidgert.harrypottermod.items.UnicornHairClass;
import snidgert.harrypottermod.items.VeelaHairClass;
import snidgert.harrypottermod.items.WerewolfFormClass;
import snidgert.harrypottermod.magiceffects.ShieldEffectClass;
import snidgert.harrypottermod.mobs.entity.EntityAragog;
import snidgert.harrypottermod.mobs.entity.EntityAugurey;
import snidgert.harrypottermod.mobs.entity.EntityBasilisk;
import snidgert.harrypottermod.mobs.entity.EntityBillywig;
import snidgert.harrypottermod.mobs.entity.EntityBird;
import snidgert.harrypottermod.mobs.entity.EntityBludger;
import snidgert.harrypottermod.mobs.entity.EntityBoggartDementor;
import snidgert.harrypottermod.mobs.entity.EntityBook;
import snidgert.harrypottermod.mobs.entity.EntityBowtruckle;
import snidgert.harrypottermod.mobs.entity.EntityBundimun;
import snidgert.harrypottermod.mobs.entity.EntityCabinet;
import snidgert.harrypottermod.mobs.entity.EntityCabinet2;
import snidgert.harrypottermod.mobs.entity.EntityCatForm;
import snidgert.harrypottermod.mobs.entity.EntityCentaur;
import snidgert.harrypottermod.mobs.entity.EntityChizpurfle;
import snidgert.harrypottermod.mobs.entity.EntityClabbert;
import snidgert.harrypottermod.mobs.entity.EntityDementor;
import snidgert.harrypottermod.mobs.entity.EntityDemiguise;
import snidgert.harrypottermod.mobs.entity.EntityDogForm;
import snidgert.harrypottermod.mobs.entity.EntityDugbog;
import snidgert.harrypottermod.mobs.entity.EntityFairy;
import snidgert.harrypottermod.mobs.entity.EntityFalconForm;
import snidgert.harrypottermod.mobs.entity.EntityFiendfyreDragon;
import snidgert.harrypottermod.mobs.entity.EntityFireCrab;
import snidgert.harrypottermod.mobs.entity.EntityFlobberworm;
import snidgert.harrypottermod.mobs.entity.EntityFluffy;
import snidgert.harrypottermod.mobs.entity.EntityFlyingBroomstick;
import snidgert.harrypottermod.mobs.entity.EntityFordAnglia;
import snidgert.harrypottermod.mobs.entity.EntityFwooper;
import snidgert.harrypottermod.mobs.entity.EntityGhost;
import snidgert.harrypottermod.mobs.entity.EntityGhoul;
import snidgert.harrypottermod.mobs.entity.EntityGnome;
import snidgert.harrypottermod.mobs.entity.EntityGoblin;
import snidgert.harrypottermod.mobs.entity.EntityGoldenSnitch;
import snidgert.harrypottermod.mobs.entity.EntityGraphorn;
import snidgert.harrypottermod.mobs.entity.EntityGriffin;
import snidgert.harrypottermod.mobs.entity.EntityGrindylow;
import snidgert.harrypottermod.mobs.entity.EntityHippocampus;
import snidgert.harrypottermod.mobs.entity.EntityHippogriff;
import snidgert.harrypottermod.mobs.entity.EntityHorklump;
import snidgert.harrypottermod.mobs.entity.EntityHorntail;
import snidgert.harrypottermod.mobs.entity.EntityHouseElf;
import snidgert.harrypottermod.mobs.entity.EntityImp;
import snidgert.harrypottermod.mobs.entity.EntityImperioMob;
import snidgert.harrypottermod.mobs.entity.EntityJarvey;
import snidgert.harrypottermod.mobs.entity.EntityJobberknoll;
import snidgert.harrypottermod.mobs.entity.EntityKelpie;
import snidgert.harrypottermod.mobs.entity.EntityKey;
import snidgert.harrypottermod.mobs.entity.EntityKnarl;
import snidgert.harrypottermod.mobs.entity.EntityKneazle;
import snidgert.harrypottermod.mobs.entity.EntityLeprechaun;
import snidgert.harrypottermod.mobs.entity.EntityLevitate;
import snidgert.harrypottermod.mobs.entity.EntityMasterKey;
import snidgert.harrypottermod.mobs.entity.EntityMermaid;
import snidgert.harrypottermod.mobs.entity.EntityMoke;
import snidgert.harrypottermod.mobs.entity.EntityMonsterBook;
import snidgert.harrypottermod.mobs.entity.EntityMotorbike;
import snidgert.harrypottermod.mobs.entity.EntityMotorbike2;
import snidgert.harrypottermod.mobs.entity.EntityNagini;
import snidgert.harrypottermod.mobs.entity.EntityNogtail;
import snidgert.harrypottermod.mobs.entity.EntityNundu;
import snidgert.harrypottermod.mobs.entity.EntityOccamy;
import snidgert.harrypottermod.mobs.entity.EntityOwlForm;
import snidgert.harrypottermod.mobs.entity.EntityPatronus;
import snidgert.harrypottermod.mobs.entity.EntityPhoenix;
import snidgert.harrypottermod.mobs.entity.EntityPhoenixForm;
import snidgert.harrypottermod.mobs.entity.EntityPixie;
import snidgert.harrypottermod.mobs.entity.EntityPuffskein;
import snidgert.harrypottermod.mobs.entity.EntityQuaffle;
import snidgert.harrypottermod.mobs.entity.EntityQuintaped;
import snidgert.harrypottermod.mobs.entity.EntityRamora;
import snidgert.harrypottermod.mobs.entity.EntityRatForm;
import snidgert.harrypottermod.mobs.entity.EntityRavenForm;
import snidgert.harrypottermod.mobs.entity.EntityRedCap;
import snidgert.harrypottermod.mobs.entity.EntityReem;
import snidgert.harrypottermod.mobs.entity.EntityRunespoor;
import snidgert.harrypottermod.mobs.entity.EntityShield;
import snidgert.harrypottermod.mobs.entity.EntitySnake;
import snidgert.harrypottermod.mobs.entity.EntitySnidget;
import snidgert.harrypottermod.mobs.entity.EntitySnidgetForm;
import snidgert.harrypottermod.mobs.entity.EntityStagForm;
import snidgert.harrypottermod.mobs.entity.EntityStoneSoldier;
import snidgert.harrypottermod.mobs.entity.EntityTebo;
import snidgert.harrypottermod.mobs.entity.EntityThestral;
import snidgert.harrypottermod.mobs.entity.EntityTroll;
import snidgert.harrypottermod.mobs.entity.EntityUkaranianIronbelly;
import snidgert.harrypottermod.mobs.entity.EntityUnicorn;
import snidgert.harrypottermod.mobs.entity.EntityVeela;
import snidgert.harrypottermod.mobs.entity.EntityWerewolf;
import snidgert.harrypottermod.mobs.entity.EntityWerewolfMob;
import snidgert.harrypottermod.mobs.entity.EntityWingedHorse;
import snidgert.harrypottermod.projectiles.AraniaExumaiProjectile;
import snidgert.harrypottermod.projectiles.AvadakedavraProjectile;
import snidgert.harrypottermod.projectiles.ConfringoProjectile;
import snidgert.harrypottermod.projectiles.ConfringoStrongProjectile;
import snidgert.harrypottermod.projectiles.ConfundoProjectile;
import snidgert.harrypottermod.projectiles.ConfundoStrongProjectile;
import snidgert.harrypottermod.projectiles.CrucioProjectile;
import snidgert.harrypottermod.projectiles.CrucioStrongProjectile;
import snidgert.harrypottermod.projectiles.ExpelliarmusProjectile;
import snidgert.harrypottermod.projectiles.ExpelliarmusStrongProjectile;
import snidgert.harrypottermod.projectiles.ImperioProjectile;
import snidgert.harrypottermod.projectiles.IncendioProjectile;
import snidgert.harrypottermod.projectiles.LevicorpusProjectile;
import snidgert.harrypottermod.projectiles.LevicorpusStrongProjectile;
import snidgert.harrypottermod.projectiles.PatronusProjectile;
import snidgert.harrypottermod.projectiles.PatronusStrongProjectile;
import snidgert.harrypottermod.projectiles.ReductoProjectile;
import snidgert.harrypottermod.projectiles.ReductoStrongProjectile;
import snidgert.harrypottermod.projectiles.SectumsempraProjectile;
import snidgert.harrypottermod.projectiles.SectumsempraStrongProjectile;
import snidgert.harrypottermod.projectiles.StunProjectile;
import snidgert.harrypottermod.projectiles.StunStrongProjectile;
import snidgert.harrypottermod.projectiles.StupefyProjectile;
import snidgert.harrypottermod.projectiles.StupefyStrongProjectile;
import snidgert.harrypottermod.spellsystem.MagicLeveling;
import snidgert.harrypottermod.tileentities.TileEntityBoggartChestLocked;
import snidgert.harrypottermod.tileentities.TileEntityBoggartChestOpen;
import snidgert.harrypottermod.tileentities.TileEntityCabinet;
import snidgert.harrypottermod.tileentities.TileEntityCrystalball;
import snidgert.harrypottermod.tileentities.TileEntityCup;
import snidgert.harrypottermod.tileentities.TileEntityDarkMarkClass;
import snidgert.harrypottermod.tileentities.TileEntityDiadem;
import snidgert.harrypottermod.tileentities.TileEntityDiary;
import snidgert.harrypottermod.tileentities.TileEntityGOF;
import snidgert.harrypottermod.tileentities.TileEntityGoldenEgg;
import snidgert.harrypottermod.tileentities.TileEntityGoldenEggOpen;
import snidgert.harrypottermod.tileentities.TileEntityHand;
import snidgert.harrypottermod.tileentities.TileEntityHat;
import snidgert.harrypottermod.tileentities.TileEntityLocket;
import snidgert.harrypottermod.tileentities.TileEntityMirror;
import snidgert.harrypottermod.tileentities.TileEntityPensieve;
import snidgert.harrypottermod.tileentities.TileEntityPensievePlane;
import snidgert.harrypottermod.tileentities.TileEntityRing;
import snidgert.harrypottermod.tileentities.TileEntityStoneSoldierBlock;
import snidgert.harrypottermod.tileentities.TileEntityTriCup;
import snidgert.harrypottermod.tileentities.TileEntityWandCrafter;
import snidgert.harrypottermod.tools.SwordofGryffindorClass;
import snidgert.harrypottermod.wands.DPSWandClass;
import snidgert.harrypottermod.wands.ElderWandClass;
import snidgert.harrypottermod.wands.SupportWandClass;
import snidgert.harrypottermod.wands.TankWandClass;
import snidgert.harrypottermod.woodwands.BirchAcromantulaClass;
import snidgert.harrypottermod.woodwands.BirchAugureylass;
import snidgert.harrypottermod.woodwands.BirchBasiliskClass;
import snidgert.harrypottermod.woodwands.BirchBillywigClass;
import snidgert.harrypottermod.woodwands.BirchBoomslangClass;
import snidgert.harrypottermod.woodwands.BirchChimaeraClass;
import snidgert.harrypottermod.woodwands.BirchDemiguiseClass;
import snidgert.harrypottermod.woodwands.BirchDoxyClass;
import snidgert.harrypottermod.woodwands.BirchDragonClass;
import snidgert.harrypottermod.woodwands.BirchErumpentClass;
import snidgert.harrypottermod.woodwands.BirchFairyClass;
import snidgert.harrypottermod.woodwands.BirchFwooperClass;
import snidgert.harrypottermod.woodwands.BirchHippogriffClass;
import snidgert.harrypottermod.woodwands.BirchKelpieClass;
import snidgert.harrypottermod.woodwands.BirchPhoenixClass;
import snidgert.harrypottermod.woodwands.BirchUnicornClass;
import snidgert.harrypottermod.woodwands.BirchVeelaClass;
import snidgert.harrypottermod.woodwands.OakAcromantulaClass;
import snidgert.harrypottermod.woodwands.OakAugureyClass;
import snidgert.harrypottermod.woodwands.OakBasiliskClass;
import snidgert.harrypottermod.woodwands.OakBillywigClass;
import snidgert.harrypottermod.woodwands.OakBoomslangClass;
import snidgert.harrypottermod.woodwands.OakChimaeraClass;
import snidgert.harrypottermod.woodwands.OakDemiguiseClass;
import snidgert.harrypottermod.woodwands.OakDoxyClass;
import snidgert.harrypottermod.woodwands.OakDragonClass;
import snidgert.harrypottermod.woodwands.OakErumpentClass;
import snidgert.harrypottermod.woodwands.OakFairyClass;
import snidgert.harrypottermod.woodwands.OakFwooperClass;
import snidgert.harrypottermod.woodwands.OakHippogriffClass;
import snidgert.harrypottermod.woodwands.OakKelpieClass;
import snidgert.harrypottermod.woodwands.OakPhoenixClass;
import snidgert.harrypottermod.woodwands.OakUnicornClass;
import snidgert.harrypottermod.woodwands.OakVeelaClass;
import snidgert.harrypottermod.woodwands.RowanPhoenixClass;

@Mod(modid = "harrypottermod", name = "Harry Potter Mod", version = "v2.0")
public class MainClass {
	@SidedProxy(clientSide = "snidgert.harrypottermod.ClientProxy", serverSide = "snidgert.harrypottermod.CommonProxy")
	public static CommonProxy proxy;
	public static int InvisibilityCloakID;
	public static int AurorChestID;
	public static int AurorLegsID;
	public static int AurorHatID;
	public static int AurorShoesID;
	public static int DeathEaterChestID;
	public static int DeathEaterLegsID;
	public static int DeathEaterHatID;
	public static int DeathEaterShoesID;
	public static int WerewolfChestID;
	public static int WerewolfLegsID;
	public static int WerewolfHeadID;
	public static int WerewolfFeetID;
	public static int startEntityId = 300;
	public static final String MODID = "harrypottermod";
	public static final String NAME = "Harry Potter Mod";
	public static final String VERSION = "v2.0";
	@Mod.Instance("harrypottermod")
	public static MainClass instance;
	private static int modGuiIndex = 0;
	public static final int GUI_ITEM_INV = MainClass.modGuiIndex++;;
	public static final int Spell = 2;
	public static final int RemembrallGui = 3;
	public static final int WandCrafterGUI = 4;
	public static CreativeTabs SpellTab;
	public static CreativeTabs MagicFood;
	public static CreativeTabs MagicItems;
	public static CreativeTabs MagicMaterials;
	public static CreativeTabs WandCrafting;
	public static Item.ToolMaterial MagicWeaponMaterial;
	public static ItemArmor.ArmorMaterial MagicArmorMaterial;
	public static Item.ToolMaterial TridentMaterial;
	public static ItemArmor.ArmorMaterial AurorArmor;
	public static ItemArmor.ArmorMaterial DeathEaterArmor;
	public static ItemArmor.ArmorMaterial WerewolfFur;
	public WizardWorldGen eventWorldGen;
	public static Potion ShieldEffect;
	public static Block RubyOre;
	public static Block SilverOre;
	public static Block Brick;
	public static Block Marble;
	public static Block MarblePillar;
	public static Block BlackMarble;
	public static Block SmoothMarble;
	public static Block SmoothBlackMarble;
	public static Block BlackMarbleBrick;
	public static Block DarkMark;
	public static Block BrokenGlass;
	public static Block Stun;
	public static Block Cup;
	public static Block Crystalball;
	public static Block TriCup;
	public static Block WingardiumLeviosaBlock;
	public static Block Diadem;
	public static Block Diary;
	public static Block GoldenEgg;
	public static Block GoldenEggOpen;
	public static Block PensievePlane;
	public static Block Pensieve;
	public static Block Locket;
	public static Block Ring;
	public static Block Hand;
	public static Block Mirror;
	public static Block TorchOff;
	public static Block LampOff;
	public static Block GlowstoneOff;
	public static Block GOF;
	public static Block Cabinet;
	public static Block EveryFlavourBeans;
	public static Block Hat;
	public static Block MagicCauldron;
	public static Block BoggartChestLocked;
	public static Block BoggartChestOpen;
	public static Block WandCrafterIdle;
	public static Block WandCrafterActive;
	public static Block MagicPowerOre;
	public static Block AcromantulaWeb;
	public static Block StoneSoldierBlock;
	public static Item SilverIngot;
	public static Item Ruby;
	public static Item Bat;
	public static Item MagicBook;
	public static Item MonsterBook;
	public static Item TheGoldenSnitch;
	public static Item Quaffle;
	public static Item Bludger;
	public static Item FordAnglia;
	public static Item Motercycle;
	public static Item Motercycle2;
	public static Item Broomstick;
	public static Item MaraudersMap;
	public static Item WerewolfForm;
	public static Item PhoenixFeather;
	public static Item PStone;
	public static Item Deluminator;
	public static Item PutOuter;
	public static Item Penknife;
	public static Item ItemStore;
	public static Item Key;
	public static Item MasterKey;
	public static Item RStone;
	public static Item ElderWand;
	public static Item BFang;
	public static Item MirrorShard;
	public static Item Sock;
	public static Item HippogriffFeather;
	public static Item Remembrall;
	public static Item WoodWand;
	public static Item OakStick;
	public static Item BirchStick;
	public static Item BirchPhoenix;
	public static Item OakPhoenix;
	public static Item MagicPower;
	public static Item BirchHippogriff;
	public static Item OakHippogriff;
	public static Item DragonHeartString;
	public static Item BirchDragon;
	public static Item OakDragon;
	public static Item BasiliskScale;
	public static Item BirchBasilisk;
	public static Item OakBasilisk;
	public static Item BirchAcromantula;
	public static Item OakAcromantula;
	public static Item UnicornHair;
	public static Item BirchUnicorn;
	public static Item OakUnicorn;
	public static Item BillywigStinger;
	public static Item BirchBillywig;
	public static Item OakBillywig;
	public static Item FairyWing;
	public static Item BirchFairy;
	public static Item OakFairy;
	public static Item AugureyFeather;
	public static Item BirchAugurey;
	public static Item OakAugurey;
	public static Item BoomslangVenom;
	public static Item BirchBoomslang;
	public static Item OakBoomslang;
	public static Item ErumpentHide;
	public static Item BirchErumpent;
	public static Item OakErumpent;
	public static Item KelpieHair;
	public static Item BirchKelpie;
	public static Item OakKelpie;
	public static Item DemiguiseHair;
	public static Item BirchDemiguise;
	public static Item OakDemiguise;
	public static Item VeelaHair;
	public static Item BirchVeela;
	public static Item OakVeela;
	public static Item DoxyWing;
	public static Item BirchDoxy;
	public static Item OakDoxy;
	public static Item FwooperFeather;
	public static Item BirchFwooper;
	public static Item OakFwooper;
	public static Item ChimaeraScaleFragment;
	public static Item BirchChimaera;
	public static Item OakChimaera;
	public static Item RowanStick;
	public static Item RowanPhoenix;
	public static Item Galleon;
	public static Item Knut;
	public static Item Sickle;
	public static Item InvisibilityCloak;
	public static Item DPSWandClass;
	public static Item TankWandClass;
	public static Item SupportWandClass;
	public static Item Gillyweed;
	public static Item Bean1;
	public static Item Bean2;
	public static Item Bean3;
	public static Item Bean4;
	public static Item Bean5;
	public static Item Bean6;
	public static Item Bean7;
	public static Item Bean8;
	public static Item Bean9;
	public static Item Bean10;
	public static Item ChocolateFrog;
	public static Item TimeTurner;
	public static Item ButterBeer;
	public static Item TeboRaw;
	public static Item TeboCooked;
	public static Item NogtailRaw;
	public static Item NogtailCooked;
	public static Item RamoraRaw;
	public static Item RamoraCooked;
	public static Item SwordofGryffindor;
	public static Item Trident;
	public static Item CentaurBow;
	public static Item AurorLegs;
	public static Item AurorChest;
	public static Item AurorHat;
	public static Item AurorShoes;
	public static Item DeathEaterLegs;
	public static Item DeathEaterChest;
	public static Item DeathEaterHat;
	public static Item DeathEaterShoes;
	public static Item WerewolfLegs;
	public static Item WerewolfChest;
	public static Item WerewolfHead;
	public static Item WerewolfFeet;

	public MainClass() {

	}

	public void Init(final FMLInitializationEvent event) {
		GameRegistry.registerTileEntity(TileEntityWandCrafter.class, "TileEntityWandCrafter");
	}

	@Mod.EventHandler
	public void PreInit(final FMLPreInitializationEvent preEvent) {

		MainClass.SpellTab = new SpellTabClass(CreativeTabs.getNextID(), "Wands");
		MainClass.MagicFood = new MagicFoodClass(CreativeTabs.getNextID(), "MagicFood");
		MainClass.MagicItems = new MagicItemsClass(CreativeTabs.getNextID(), "MagicItems");
		MainClass.MagicMaterials = new MagicMaterialsClass(CreativeTabs.getNextID(), "MagicMaterials");
		MainClass.WandCrafting = new WandCraftingClass(CreativeTabs.getNextID(), "WandCrafting");
		MainClass.MagicWeaponMaterial = EnumHelper.addToolMaterial("MagicWeaponMaterial", 10, 999999999, 20.0f, 9.0f, 0);
		MainClass.MagicArmorMaterial = EnumHelper.addArmorMaterial("MagicArmorMaterial", 999999999, new int[] { 999999999, 999999999, 999999999, 999999999 }, 0);
		MainClass.TridentMaterial = EnumHelper.addToolMaterial("TridentMaterial", 5, 5000, 10.0f, 5.0f, 0);
		MainClass.AurorArmor = EnumHelper.addArmorMaterial("AurorArmor", 100, new int[] { 20, 60, 40, 20 }, 30);
		MainClass.DeathEaterArmor = EnumHelper.addArmorMaterial("DeathEaterArmor", 100, new int[] { 10, 30, 20, 10 }, 0);
		MainClass.WerewolfFur = EnumHelper.addArmorMaterial("WerewolfFur", 100, new int[] { 30, 80, 60, 30 }, 0);
		MainClass.ShieldEffect = new ShieldEffectClass(4, true, 4866583).setPotionName("potion.Shield");
		MainClass.RubyOre = new RubyOreClass(Material.rock).setBlockName("RubyOre").setCreativeTab(MainClass.MagicMaterials);
		MainClass.SilverOre = new SilverOreClass(Material.rock).setBlockName("SilverOre").setCreativeTab(MainClass.MagicMaterials);
		MainClass.Brick = new BrickClass(Material.rock).setBlockName("Brick").setCreativeTab(MainClass.MagicMaterials);
		MainClass.Marble = new MarbleClass(Material.rock).setBlockName("Marble").setCreativeTab(MainClass.MagicMaterials);
		MainClass.MarblePillar = new MarblePillarClass(Material.rock).setBlockName("MarblePillar").setCreativeTab(MainClass.MagicMaterials);
		MainClass.BlackMarble = new BlackMarbleClass(Material.rock).setBlockName("BlackMarble").setCreativeTab(MainClass.MagicMaterials);
		MainClass.SmoothMarble = new SmoothMarbleClass(Material.rock).setBlockName("SmoothMarble").setCreativeTab(MainClass.MagicMaterials);
		MainClass.SmoothBlackMarble = new SmoothBlackMarbleClass(Material.rock).setBlockName("SmoothBlackMarble").setCreativeTab(MainClass.MagicMaterials);
		MainClass.BlackMarbleBrick = new BlackMarbleBrickClass(Material.rock).setBlockName("BlackMarbleBrick").setCreativeTab(MainClass.MagicMaterials);
		MainClass.DarkMark = new DarkMarkClass(Material.glass).setBlockName("DarkMark");
		MainClass.BrokenGlass = new BrokenGlassClass(Material.glass).setBlockName("BrokenGlass").setCreativeTab(MainClass.MagicItems);
		MainClass.Stun = new StunClass(Material.web).setBlockName("Stun").setCreativeTab((CreativeTabs) null);
		MainClass.Cup = new CupClass(Material.iron).setBlockName("Cup").setCreativeTab(MainClass.MagicItems);
		MainClass.Crystalball = new CrystalballClass(Material.glass).setBlockName("Crystalball").setCreativeTab(MainClass.MagicItems);
		MainClass.TriCup = new TriCupClass(Material.glass).setBlockName("TriCup").setCreativeTab(MainClass.MagicItems);
		MainClass.WingardiumLeviosaBlock = new WingardiumLeviosaBlockClass(Material.rock).setBlockName("WingardiumLeviosaBlock").setCreativeTab(MainClass.MagicItems);
		MainClass.Diadem = new DiademClass(Material.iron).setBlockName("Diadem").setCreativeTab(MainClass.MagicItems);
		MainClass.Diary = new DiaryClass(Material.wood).setBlockName("Diary").setCreativeTab(MainClass.MagicItems);
		MainClass.GoldenEgg = new GoldenEggClass(Material.iron).setBlockName("GoldenEgg").setCreativeTab(MainClass.MagicItems);
		MainClass.GoldenEggOpen = new GoldenEggOpenClass(Material.iron).setBlockName("GoldenEggOpen").setCreativeTab((CreativeTabs) null);
		MainClass.PensievePlane = new PensievePlaneClass(Material.iron).setBlockName("PensievePlane").setCreativeTab(MainClass.MagicItems);
		MainClass.Pensieve = new PensieveClass(Material.iron).setBlockName("Pensieve").setCreativeTab(MainClass.MagicItems);
		MainClass.Locket = new LocketClass(Material.iron).setBlockName("Locket").setCreativeTab(MainClass.MagicItems);
		MainClass.Ring = new RingClass(Material.iron).setBlockName("Ring").setCreativeTab(MainClass.MagicItems);
		MainClass.Hand = new HandClass(Material.iron).setBlockName("Hand").setCreativeTab(MainClass.MagicItems);
		MainClass.Mirror = new MirrorClass(Material.iron).setBlockName("Mirror").setCreativeTab(MainClass.MagicItems);
		MainClass.TorchOff = new TorchOffClass().setBlockName("TorchOff").setCreativeTab((CreativeTabs) null);
		MainClass.LampOff = new LampOffClass(Material.glass).setBlockName("LampOff").setCreativeTab((CreativeTabs) null);
		MainClass.GlowstoneOff = new GlowstoneOffClass(Material.glass).setBlockName("GlowstoneOff").setCreativeTab((CreativeTabs) null);
		MainClass.GOF = new GOFClass(Material.iron).setBlockName("GOF").setCreativeTab(MainClass.MagicItems);
		MainClass.Cabinet = new CabinetClass(Material.wood).setBlockName("Cabinet").setCreativeTab(MainClass.MagicItems);
		MainClass.EveryFlavourBeans = new EveryFlavourBeansClass(Material.wood).setBlockName("EveryFlavourBeans").setCreativeTab(MainClass.MagicFood);
		MainClass.Hat = new HatClass(Material.cloth).setBlockName("Hat").setCreativeTab(MainClass.MagicItems);
		MainClass.MagicCauldron = new MagicCauldronClass().setBlockName("MagicCauldron").setCreativeTab(MainClass.MagicItems);
		MainClass.BoggartChestLocked = new BoggartChestLockedClass(Material.wood).setBlockName("BoggartChestLocked").setCreativeTab(MainClass.MagicItems);
		MainClass.BoggartChestOpen = new BoggartChestOpenClass(Material.wood).setBlockName("BoggartChestOpen").setCreativeTab((CreativeTabs) null);
		MainClass.WandCrafterIdle = new WandCrafterClass(false).setBlockName("WandCrafterIdle").setCreativeTab(MainClass.WandCrafting);
		MainClass.WandCrafterActive = new WandCrafterClass(true).setBlockName("WandCrafterActive").setCreativeTab((CreativeTabs) null);
		MainClass.MagicPowerOre = new MagicPowerOreClass(Material.rock).setBlockName("MagicPowerOre").setCreativeTab(MainClass.MagicMaterials);
		MainClass.AcromantulaWeb = new AcromantulaWebClass().setBlockName("AcromantulaWeb").setCreativeTab(MainClass.WandCrafting);
		MainClass.StoneSoldierBlock = new StoneSoldierBlockClass(Material.rock).setBlockName("StoneSoldierBlock").setCreativeTab(MainClass.MagicItems);
		MainClass.SilverIngot = new SilverIngotClass().setUnlocalizedName("SilverIngot").setCreativeTab(MainClass.MagicMaterials);
		MainClass.Ruby = new RubyClass().setUnlocalizedName("Ruby").setCreativeTab(MainClass.MagicMaterials);
		MainClass.Bat = new BatClass().setUnlocalizedName("Bat").setCreativeTab(MainClass.MagicItems);
		MainClass.MagicBook = new MagicBookClass().setUnlocalizedName("MagicBook").setCreativeTab(MainClass.MagicItems);
		MainClass.MonsterBook = new MonsterBookClass().setUnlocalizedName("MonsterBook").setCreativeTab(MainClass.MagicItems);
		MainClass.TheGoldenSnitch = new TheGoldenSnitchClass().setUnlocalizedName("TheGoldenSnitch").setCreativeTab(MainClass.MagicItems);
		MainClass.Quaffle = new QuaffleClass().setUnlocalizedName("Quaffle").setCreativeTab(MainClass.MagicItems);
		MainClass.Bludger = new BludgerClass().setUnlocalizedName("Bludger").setCreativeTab(MainClass.MagicItems);
		MainClass.FordAnglia = new FordAngliaClass().setUnlocalizedName("FordAnglia").setCreativeTab(MainClass.MagicItems);
		MainClass.Motercycle = new MotercycleClass().setUnlocalizedName("Motercycle").setCreativeTab(MainClass.MagicItems);
		MainClass.Motercycle2 = new Motercycle2Class().setUnlocalizedName("Motercycle2").setCreativeTab(MainClass.MagicItems);
		MainClass.Broomstick = new BroomstickClass().setUnlocalizedName("Broomstick").setCreativeTab(MainClass.MagicItems);
		MainClass.MaraudersMap = new MaraudersMapClass().setUnlocalizedName("MaraudersMap").setCreativeTab(MainClass.MagicItems);
		MainClass.WerewolfForm = new WerewolfFormClass().setUnlocalizedName("WerewolfForm").setCreativeTab(MainClass.MagicItems);
		MainClass.PhoenixFeather = new PhoenixFeatherClass().setUnlocalizedName("PhoenixFeather").setCreativeTab(MainClass.WandCrafting);
		MainClass.PStone = new PStoneClass().setUnlocalizedName("PStone").setCreativeTab(MainClass.MagicItems);
		MainClass.Deluminator = new DeluminatorClass().setUnlocalizedName("Deluminator").setCreativeTab((CreativeTabs) null);
		MainClass.PutOuter = new PutOuterClass().setUnlocalizedName("PutOuter").setCreativeTab(MainClass.MagicItems);
		MainClass.Penknife = new PenknifeClass().setUnlocalizedName("Penknife").setCreativeTab(MainClass.MagicItems);
		MainClass.ItemStore = new ItemStoreClass().setUnlocalizedName("ItemStore").setCreativeTab(MainClass.MagicItems);
		MainClass.Key = new KeyClass().setUnlocalizedName("Key").setCreativeTab(MainClass.MagicItems);
		MainClass.MasterKey = new MasterKeyClass().setUnlocalizedName("MasterKey").setCreativeTab(MainClass.MagicItems);
		MainClass.RStone = new RStoneClass().setUnlocalizedName("RStone").setCreativeTab(MainClass.MagicItems);
		MainClass.ElderWand = new ElderWandClass().setUnlocalizedName("ElderWand").setCreativeTab(MainClass.SpellTab);
		MainClass.BFang = new BFangClass().setUnlocalizedName("BFang").setCreativeTab(MainClass.MagicItems);
		MainClass.MirrorShard = new MirrorShardClass().setUnlocalizedName("MirrorShard").setCreativeTab(MainClass.MagicItems);
		MainClass.Sock = new SockClass().setUnlocalizedName("Sock").setCreativeTab(MainClass.MagicItems);
		MainClass.HippogriffFeather = new HippogriffFeatherClass().setUnlocalizedName("HippogriffFeather").setCreativeTab(MainClass.WandCrafting);
		MainClass.Remembrall = new RemembrallClass().setUnlocalizedName("Remembrall").setCreativeTab(MainClass.MagicItems);
		MainClass.OakStick = new OakStickClass().setUnlocalizedName("OakStick").setCreativeTab(MainClass.WandCrafting);
		MainClass.BirchStick = new BirchStickClass().setUnlocalizedName("BirchStick").setCreativeTab(MainClass.WandCrafting);
		MainClass.BirchPhoenix = new BirchPhoenixClass().setUnlocalizedName("BirchPhoenix").setCreativeTab(MainClass.SpellTab);
		MainClass.OakPhoenix = new OakPhoenixClass().setUnlocalizedName("OakPhoenix").setCreativeTab(MainClass.SpellTab);
		MainClass.MagicPower = new MagicPowerClass().setUnlocalizedName("MagicPower").setCreativeTab(MainClass.WandCrafting);
		MainClass.BirchHippogriff = new BirchHippogriffClass().setUnlocalizedName("BirchHippogriff").setCreativeTab(MainClass.SpellTab);
		MainClass.OakHippogriff = new OakHippogriffClass().setUnlocalizedName("OakHippogriff").setCreativeTab(MainClass.SpellTab);
		MainClass.DragonHeartString = new DragonHeartStringClass().setUnlocalizedName("DragonHeartString").setCreativeTab(MainClass.WandCrafting);
		MainClass.BirchDragon = new BirchDragonClass().setUnlocalizedName("BirchDragon").setCreativeTab(MainClass.SpellTab);
		MainClass.OakDragon = new OakDragonClass().setUnlocalizedName("OakDragon").setCreativeTab(MainClass.SpellTab);
		MainClass.BasiliskScale = new BasiliskScaleClass().setUnlocalizedName("BasiliskScale").setCreativeTab(MainClass.WandCrafting);
		MainClass.BirchBasilisk = new BirchBasiliskClass().setUnlocalizedName("BirchBasilisk").setCreativeTab(MainClass.SpellTab);
		MainClass.OakBasilisk = new OakBasiliskClass().setUnlocalizedName("OakBasilisk").setCreativeTab(MainClass.SpellTab);
		MainClass.BirchAcromantula = new BirchAcromantulaClass().setUnlocalizedName("BirchAcromantula").setCreativeTab(MainClass.SpellTab);
		MainClass.OakAcromantula = new OakAcromantulaClass().setUnlocalizedName("OakAcromantula").setCreativeTab(MainClass.SpellTab);
		MainClass.UnicornHair = new UnicornHairClass().setUnlocalizedName("UnicornHair").setCreativeTab(MainClass.WandCrafting);
		MainClass.BirchUnicorn = new BirchUnicornClass().setUnlocalizedName("BirchUnicorn").setCreativeTab(MainClass.SpellTab);
		MainClass.OakUnicorn = new OakUnicornClass().setUnlocalizedName("OakUnicorn").setCreativeTab(MainClass.SpellTab);
		MainClass.BillywigStinger = new BillywigStingerClass().setUnlocalizedName("BillywigStinger").setCreativeTab(MainClass.WandCrafting);
		MainClass.BirchBillywig = new BirchBillywigClass().setUnlocalizedName("BirchBillywig").setCreativeTab(MainClass.SpellTab);
		MainClass.OakBillywig = new OakBillywigClass().setUnlocalizedName("OakBillywig").setCreativeTab(MainClass.SpellTab);
		MainClass.FairyWing = new FairyWingClass().setUnlocalizedName("FairyWing").setCreativeTab(MainClass.WandCrafting);
		MainClass.BirchFairy = new BirchFairyClass().setUnlocalizedName("BirchFairy").setCreativeTab(MainClass.SpellTab);
		MainClass.OakFairy = new OakFairyClass().setUnlocalizedName("OakFairy").setCreativeTab(MainClass.SpellTab);
		MainClass.AugureyFeather = new AugureyFeatherClass().setUnlocalizedName("AugureyFeather").setCreativeTab(MainClass.WandCrafting);
		MainClass.BirchAugurey = new BirchAugureylass().setUnlocalizedName("BirchAugurey").setCreativeTab(MainClass.SpellTab);
		MainClass.OakAugurey = new OakAugureyClass().setUnlocalizedName("OakAugurey").setCreativeTab(MainClass.SpellTab);
		MainClass.BoomslangVenom = new BoomslangVenomClass().setUnlocalizedName("BoomslangVenom").setCreativeTab(MainClass.WandCrafting);
		MainClass.BirchBoomslang = new BirchBoomslangClass().setUnlocalizedName("BirchBoomslang").setCreativeTab(MainClass.SpellTab);
		MainClass.OakBoomslang = new OakBoomslangClass().setUnlocalizedName("OakBoomslang").setCreativeTab(MainClass.SpellTab);
		MainClass.ErumpentHide = new ErumpentHideClass().setUnlocalizedName("ErumpentHide").setCreativeTab(MainClass.WandCrafting);
		MainClass.BirchErumpent = new BirchErumpentClass().setUnlocalizedName("BirchErumpent").setCreativeTab(MainClass.SpellTab);
		MainClass.OakErumpent = new OakErumpentClass().setUnlocalizedName("OakErumpent").setCreativeTab(MainClass.SpellTab);
		MainClass.KelpieHair = new KelpieHairClass().setUnlocalizedName("KelpieHair").setCreativeTab(MainClass.WandCrafting);
		MainClass.BirchKelpie = new BirchKelpieClass().setUnlocalizedName("BirchKelpie").setCreativeTab(MainClass.SpellTab);
		MainClass.OakKelpie = new OakKelpieClass().setUnlocalizedName("OakKelpie").setCreativeTab(MainClass.SpellTab);
		MainClass.DemiguiseHair = new DemiguiseHairClass().setUnlocalizedName("DemiguiseHair").setCreativeTab(MainClass.WandCrafting);
		MainClass.BirchDemiguise = new BirchDemiguiseClass().setUnlocalizedName("BirchDemiguise").setCreativeTab(MainClass.SpellTab);
		MainClass.OakDemiguise = new OakDemiguiseClass().setUnlocalizedName("OakDemiguise").setCreativeTab(MainClass.SpellTab);
		MainClass.VeelaHair = new VeelaHairClass().setUnlocalizedName("VeelaHair").setCreativeTab(MainClass.WandCrafting);
		MainClass.BirchVeela = new BirchVeelaClass().setUnlocalizedName("BirchVeela").setCreativeTab(MainClass.SpellTab);
		MainClass.OakVeela = new OakVeelaClass().setUnlocalizedName("OakVeela").setCreativeTab(MainClass.SpellTab);
		MainClass.DoxyWing = new DoxyWingClass().setUnlocalizedName("DoxyWing").setCreativeTab(MainClass.WandCrafting);
		MainClass.BirchDoxy = new BirchDoxyClass().setUnlocalizedName("BirchDoxy").setCreativeTab(MainClass.SpellTab);
		MainClass.OakDoxy = new OakDoxyClass().setUnlocalizedName("OakDoxy").setCreativeTab(MainClass.SpellTab);
		MainClass.FwooperFeather = new FwooperFeatherClass().setUnlocalizedName("FwooperFeather").setCreativeTab(MainClass.WandCrafting);
		MainClass.BirchFwooper = new BirchFwooperClass().setUnlocalizedName("BirchFwooper").setCreativeTab(MainClass.SpellTab);
		MainClass.OakFwooper = new OakFwooperClass().setUnlocalizedName("OakFwooper").setCreativeTab(MainClass.SpellTab);
		MainClass.ChimaeraScaleFragment = new ChimaeraScaleFragmentClass().setUnlocalizedName("ChimaeraScaleFragment").setCreativeTab(MainClass.WandCrafting);
		MainClass.BirchChimaera = new BirchChimaeraClass().setUnlocalizedName("BirchChimaera").setCreativeTab(MainClass.SpellTab);
		MainClass.OakChimaera = new OakChimaeraClass().setUnlocalizedName("OakChimaera").setCreativeTab(MainClass.SpellTab);
		MainClass.RowanStick = new RowanStickClass().setUnlocalizedName("RowanStick").setCreativeTab(MainClass.WandCrafting);
		MainClass.RowanPhoenix = new RowanPhoenixClass().setUnlocalizedName("RowanPhoenix").setCreativeTab(MainClass.SpellTab);
		MainClass.Galleon = new GalleonClass().setUnlocalizedName("Galleon").setCreativeTab(MainClass.MagicItems);
		MainClass.Knut = new KnutClass().setUnlocalizedName("Knut").setCreativeTab(MainClass.MagicItems);
		MainClass.Sickle = new SickleClass().setUnlocalizedName("Sickle").setCreativeTab(MainClass.MagicItems);
		MainClass.InvisibilityCloak = new InvisibilityCloakArmorClass(MainClass.MagicArmorMaterial, MainClass.InvisibilityCloakID, 1).setUnlocalizedName("InvisibilityCloak")
				.setCreativeTab(MainClass.MagicItems);
		MainClass.DPSWandClass = new DPSWandClass().setUnlocalizedName("DPSWandClass").setCreativeTab(MainClass.SpellTab);
		MainClass.TankWandClass = new TankWandClass().setUnlocalizedName("TankWandClass").setCreativeTab(MainClass.SpellTab);
		MainClass.SupportWandClass = new SupportWandClass().setUnlocalizedName("SupportWandClass").setCreativeTab(MainClass.SpellTab);
		MainClass.Gillyweed = new GillyweedClass(999999999, 1.0E9f, false).setPotionEffect(Potion.waterBreathing.id, 3600, 1, 0.8f).setUnlocalizedName("Gillyweed").setCreativeTab(MainClass.MagicFood);
		MainClass.Bean1 = new Bean1Class(999999999, 1.0E9f, false).setUnlocalizedName("Bean1").setCreativeTab((CreativeTabs) null);
		MainClass.Bean2 = new Bean2Class(999999999, 1.0E9f, false).setUnlocalizedName("Bean2").setCreativeTab((CreativeTabs) null);
		MainClass.Bean3 = new Bean3Class(999999999, 1.0E9f, false).setUnlocalizedName("Bean3").setCreativeTab((CreativeTabs) null);
		MainClass.Bean4 = new Bean4Class(999999999, 1.0E9f, false).setUnlocalizedName("Bean4").setCreativeTab((CreativeTabs) null);
		MainClass.Bean5 = new Bean5Class(999999999, 1.0E9f, false).setUnlocalizedName("Bean5").setCreativeTab((CreativeTabs) null);
		MainClass.Bean6 = new Bean6Class(999999999, 1.0E9f, false).setUnlocalizedName("Bean6").setCreativeTab((CreativeTabs) null);
		MainClass.Bean7 = new Bean7Class(999999999, 1.0E9f, false).setUnlocalizedName("Bean7").setCreativeTab((CreativeTabs) null);
		MainClass.Bean8 = new Bean8Class(999999999, 1.0E9f, false).setUnlocalizedName("Bean8").setCreativeTab((CreativeTabs) null);
		MainClass.Bean9 = new Bean9Class(999999999, 1.0E9f, false).setUnlocalizedName("Bean9").setCreativeTab((CreativeTabs) null);
		MainClass.Bean10 = new Bean10Class(999999999, 1.0E9f, false).setUnlocalizedName("Bean10").setCreativeTab((CreativeTabs) null);
		MainClass.ChocolateFrog = new ChocolateFrogClass(999999999, 1.0E9f, false).setUnlocalizedName("ChocolateFrog").setCreativeTab(MainClass.MagicFood);
		MainClass.TimeTurner = new TimeTurnerClass(0, 1.0f, false).setUnlocalizedName("TimeTurner").setCreativeTab(MainClass.MagicItems);
		MainClass.ButterBeer = new ButterBeerClass(999999999, 1.0E9f, false).setPotionEffect(Potion.confusion.id, 30, 1, 0.8f).setUnlocalizedName("ButterBeer").setCreativeTab(MainClass.MagicFood);
		MainClass.TeboRaw = new TeboRawClass(2, 2.0f, false).setPotionEffect(Potion.hunger.id, 30, 1, 0.8f).setUnlocalizedName("TeboRaw").setCreativeTab(MainClass.MagicFood);
		MainClass.TeboCooked = new TeboCookedClass(999999999, 1.0E9f, false).setUnlocalizedName("TeboCooked").setCreativeTab(MainClass.MagicFood);
		MainClass.NogtailRaw = new NogtailRawClass(2, 2.0f, false).setPotionEffect(Potion.hunger.id, 30, 1, 0.8f).setUnlocalizedName("NogtailRaw").setCreativeTab(MainClass.MagicFood);
		MainClass.NogtailCooked = new NogtailCookedClass(999999999, 1.0E9f, false).setUnlocalizedName("NogtailCooked").setCreativeTab(MainClass.MagicFood);
		MainClass.RamoraRaw = new RamoraRawClass(2, 2.0f, false).setPotionEffect(Potion.hunger.id, 30, 1, 0.8f).setUnlocalizedName("RamoraRaw").setCreativeTab(MainClass.MagicFood);
		MainClass.RamoraCooked = new RamoraCookedClass(999999999, 1.0E9f, false).setUnlocalizedName("RamoraCooked").setCreativeTab(MainClass.MagicFood);
		MainClass.SwordofGryffindor = new SwordofGryffindorClass(MainClass.MagicWeaponMaterial).setFull3D().setUnlocalizedName("SwordofGryffindor").setCreativeTab(MainClass.MagicItems);
		MainClass.Trident = new TridentClass(MainClass.TridentMaterial).setUnlocalizedName("Trident").setUnlocalizedName("Trident").setCreativeTab(MainClass.MagicItems);
		MainClass.AurorLegs = new AurorArmorClass(MainClass.AurorArmor, MainClass.AurorLegsID, 2).setUnlocalizedName("AurorLegs").setCreativeTab(MainClass.MagicItems);
		MainClass.AurorChest = new AurorArmorClass(MainClass.AurorArmor, MainClass.AurorChestID, 1).setUnlocalizedName("AurorChest").setCreativeTab(MainClass.MagicItems);
		MainClass.AurorHat = new AurorArmorClass(MainClass.AurorArmor, MainClass.AurorHatID, 0).setUnlocalizedName("AurorHat").setCreativeTab(MainClass.MagicItems);
		MainClass.AurorShoes = new AurorArmorClass(MainClass.AurorArmor, MainClass.AurorShoesID, 3).setUnlocalizedName("AurorShoes").setCreativeTab(MainClass.MagicItems);
		MainClass.DeathEaterLegs = new DeathEaterArmorClass(MainClass.DeathEaterArmor, MainClass.DeathEaterLegsID, 2).setUnlocalizedName("DeathEaterLegs").setCreativeTab(MainClass.MagicItems);
		MainClass.DeathEaterChest = new DeathEaterArmorClass(MainClass.DeathEaterArmor, MainClass.DeathEaterChestID, 1).setUnlocalizedName("DeathEaterChest").setCreativeTab(MainClass.MagicItems);
		MainClass.DeathEaterHat = new DeathEaterArmorClass(MainClass.DeathEaterArmor, MainClass.DeathEaterHatID, 0).setUnlocalizedName("DeathEaterHat").setCreativeTab(MainClass.MagicItems);
		MainClass.DeathEaterShoes = new DeathEaterArmorClass(MainClass.DeathEaterArmor, MainClass.DeathEaterShoesID, 3).setUnlocalizedName("DeathEaterShoes").setCreativeTab(MainClass.MagicItems);
		MainClass.WerewolfLegs = new WerewolfArmorClass(MainClass.WerewolfFur, MainClass.WerewolfLegsID, 2).setUnlocalizedName("WerewolfLegs").setCreativeTab(MainClass.MagicItems);
		MainClass.WerewolfChest = new WerewolfArmorClass(MainClass.WerewolfFur, MainClass.WerewolfChestID, 1).setUnlocalizedName("WerewolfChest").setCreativeTab(MainClass.MagicItems);
		MainClass.WerewolfHead = new WerewolfArmorClass(MainClass.WerewolfFur, MainClass.WerewolfHeadID, 0).setUnlocalizedName("WerewolfHead").setCreativeTab(MainClass.MagicItems);
		MainClass.WerewolfFeet = new WerewolfArmorClass(MainClass.WerewolfFur, MainClass.WerewolfFeetID, 3).setUnlocalizedName("WerewolfFeet").setCreativeTab(MainClass.MagicItems);


		this.eventWorldGen = new WizardWorldGen();
		GameRegistry.registerBlock(MainClass.AcromantulaWeb, "AcromantulaWeb");
		GameRegistry.registerBlock(MainClass.Brick, "Brick");
		GameRegistry.registerBlock(MainClass.StoneSoldierBlock, "StoneSoldierBlock");
		GameRegistry.registerBlock(MainClass.MarblePillar, "MarblePillar");
		GameRegistry.registerBlock(MainClass.MagicPowerOre, "MagicPowerOre");
		GameRegistry.registerBlock(MainClass.WandCrafterActive, "WandCrafterActive");
		GameRegistry.registerBlock(MainClass.WandCrafterIdle, "WandCrafterIdle");
		GameRegistry.registerBlock(MainClass.BoggartChestOpen, "BoggartChestOpen");
		GameRegistry.registerBlock(MainClass.BoggartChestLocked, "BoggartChestLocked");
		GameRegistry.registerBlock(MainClass.Marble, "Marble");
		GameRegistry.registerBlock(MainClass.BlackMarble, "BlackMarble");
		GameRegistry.registerBlock(MainClass.BlackMarbleBrick, "BlackMarbleBrick");
		GameRegistry.registerBlock(MainClass.SmoothMarble, "SmoothMarble");
		GameRegistry.registerBlock(MainClass.SmoothBlackMarble, "SmoothBlackMarble");
		GameRegistry.registerBlock(MainClass.Hat, "Hat");
		GameRegistry.registerBlock(MainClass.EveryFlavourBeans, "EveryFlavourBeans");
		GameRegistry.registerBlock(MainClass.Cabinet, "Cabinet");
		GameRegistry.registerBlock(MainClass.GOF, "GOF");
		GameRegistry.registerBlock(MainClass.GlowstoneOff, "GlowstoneOff");
		GameRegistry.registerBlock(MainClass.LampOff, "LampOff");
		GameRegistry.registerBlock(MainClass.TorchOff, "TorchOff");
		GameRegistry.registerBlock(MainClass.Mirror, "Mirror");
		GameRegistry.registerBlock(MainClass.Hand, "Hand");
		GameRegistry.registerBlock(MainClass.Ring, "Ring");
		GameRegistry.registerBlock(MainClass.Locket, "Locket");
		GameRegistry.registerBlock(MainClass.Pensieve, "Pensieve");
		GameRegistry.registerBlock(MainClass.PensievePlane, "PensievePlane");
		GameRegistry.registerBlock(MainClass.GoldenEggOpen, "GoldenEggOpen");
		GameRegistry.registerBlock(MainClass.GoldenEgg, "GoldenEgg");
		GameRegistry.registerBlock(MainClass.Diary, "Diary");
		GameRegistry.registerBlock(MainClass.Diadem, "Diadem");
		GameRegistry.registerBlock(MainClass.TriCup, "TriCup");
		GameRegistry.registerBlock(MainClass.Crystalball, "Crystalball");
		GameRegistry.registerBlock(MainClass.Cup, "Cup");
		GameRegistry.registerBlock(MainClass.RubyOre, "RubyOre");
		GameRegistry.registerBlock(MainClass.SilverOre, "SilverOre");
		GameRegistry.registerBlock(MainClass.DarkMark, "DarkMark");
		GameRegistry.registerBlock(MainClass.BrokenGlass, "BrokenGlass");
		GameRegistry.registerItem(MainClass.SwordofGryffindor, "SwordofGryffindor");
		GameRegistry.registerItem(MainClass.SilverIngot, "SilverIngot");
		GameRegistry.registerItem(MainClass.Ruby, "Ruby");
		GameRegistry.registerItem(MainClass.InvisibilityCloak, "InvisibilityCloak");
		GameRegistry.registerItem(MainClass.Gillyweed, "Gillyweed");
		GameRegistry.registerItem(MainClass.ChocolateFrog, "ChocolateFrog");
		GameRegistry.registerItem(MainClass.TimeTurner, "TimeTurner");
		GameRegistry.registerBlock(MainClass.Stun, "Stun");
		GameRegistry.registerItem(MainClass.Bat, "Bat");
		GameRegistry.registerItem(MainClass.MagicBook, "MagicBook");
		GameRegistry.registerItem(MainClass.MonsterBook, "MonsterBook");
		GameRegistry.registerBlock(MainClass.WingardiumLeviosaBlock, "WingardiumLeviosaBlock");
		GameRegistry.registerItem(MainClass.TheGoldenSnitch, "TheGoldenSnitch");
		GameRegistry.registerItem(MainClass.Quaffle, "Quaffle");
		GameRegistry.registerItem(MainClass.Bludger, "Bludger");
		GameRegistry.registerItem(MainClass.FordAnglia, "FordAnglia");
		GameRegistry.registerItem(MainClass.Motercycle, "Motercycle");
		GameRegistry.registerItem(MainClass.Motercycle2, "Motercycle2");
		GameRegistry.registerItem(MainClass.Broomstick, "Broomstick");
		GameRegistry.registerItem(MainClass.MaraudersMap, "MaraudersMap");
		GameRegistry.registerItem(MainClass.WerewolfForm, "WerewolfForm");
		GameRegistry.registerItem(MainClass.PhoenixFeather, "PhoenixFeather");
		GameRegistry.registerItem(MainClass.PStone, "PStone");
		GameRegistry.registerItem(MainClass.Deluminator, "Deluminator");
		GameRegistry.registerItem(MainClass.PutOuter, "PutOuter");
		GameRegistry.registerItem(MainClass.Penknife, "Penknife");
		GameRegistry.registerItem(MainClass.ItemStore, "ItemStore");
		GameRegistry.registerItem(MainClass.MasterKey, "MasterKey");
		GameRegistry.registerItem(MainClass.Key, "Key");
		GameRegistry.registerItem(MainClass.RStone, "RStone");
		GameRegistry.registerItem(MainClass.ElderWand, "ElderWand");
		GameRegistry.registerItem(MainClass.BFang, "BFang");
		GameRegistry.registerItem(MainClass.MirrorShard, "MirrorShard");
		GameRegistry.registerItem(MainClass.Sock, "Sock");
		GameRegistry.registerItem(MainClass.HippogriffFeather, "HippogriffFeather");
		GameRegistry.registerItem(MainClass.ButterBeer, "ButterBeer");
		GameRegistry.registerItem(MainClass.Bean1, "Bean1");
		GameRegistry.registerItem(MainClass.Bean2, "Bean2");
		GameRegistry.registerItem(MainClass.Bean3, "Bean3");
		GameRegistry.registerItem(MainClass.Bean4, "Bean4");
		GameRegistry.registerItem(MainClass.Bean5, "Bean5");
		GameRegistry.registerItem(MainClass.Bean6, "Bean6");
		GameRegistry.registerItem(MainClass.Bean7, "Bean7");
		GameRegistry.registerItem(MainClass.Bean8, "Bean8");
		GameRegistry.registerItem(MainClass.Bean9, "Bean9");
		GameRegistry.registerItem(MainClass.Bean10, "Bean10");
		GameRegistry.registerItem(MainClass.AurorLegs, "AurorLegs");
		GameRegistry.registerItem(MainClass.AurorChest, "AurorChest");
		GameRegistry.registerItem(MainClass.AurorHat, "AurorHat");
		GameRegistry.registerItem(MainClass.AurorShoes, "AurorShoes");
		GameRegistry.registerItem(MainClass.DeathEaterLegs, "DeathEaterLegs");
		GameRegistry.registerItem(MainClass.DeathEaterChest, "DeathEaterChest");
		GameRegistry.registerItem(MainClass.DeathEaterHat, "DeathEaterHat");
		GameRegistry.registerItem(MainClass.DeathEaterShoes, "DeathEaterShoes");
		GameRegistry.registerItem(MainClass.Remembrall, "Remembrall");
		GameRegistry.registerItem(MainClass.OakStick, "OakStick");
		GameRegistry.registerItem(MainClass.BirchStick, "BirchStick");
		GameRegistry.registerItem(MainClass.MagicPower, "MagicPower");
		GameRegistry.registerItem(MainClass.DragonHeartString, "DragonHeartString");
		GameRegistry.registerItem(MainClass.BasiliskScale, "BasiliskScale");
		GameRegistry.registerItem(MainClass.UnicornHair, "UnicornHair");
		GameRegistry.registerItem(MainClass.BillywigStinger, "BillywigStinger");
		GameRegistry.registerItem(MainClass.FairyWing, "FairyWing");
		GameRegistry.registerItem(MainClass.AugureyFeather, "AugureyFeather");
		GameRegistry.registerItem(MainClass.Trident, "Trident");
		GameRegistry.registerItem(MainClass.BoomslangVenom, "BoomslangVenom");
		GameRegistry.registerItem(MainClass.ErumpentHide, "ErumpentHide");
		GameRegistry.registerItem(MainClass.KelpieHair, "KelpieHair");
		GameRegistry.registerItem(MainClass.DemiguiseHair, "DemiguiseHair");
		GameRegistry.registerItem(MainClass.VeelaHair, "VeelaHair");
		GameRegistry.registerItem(MainClass.DoxyWing, "DoxyWing");
		GameRegistry.registerItem(MainClass.FwooperFeather, "FwooperFeather");
		GameRegistry.registerItem(MainClass.ChimaeraScaleFragment, "ChimaeraScaleFragment");
		GameRegistry.registerItem(MainClass.RowanStick, "RowanStick");
		GameRegistry.registerItem(MainClass.Galleon, "Galleon");
		GameRegistry.registerItem(MainClass.Knut, "Knut");
		GameRegistry.registerItem(MainClass.Sickle, "Sickle");
		GameRegistry.registerItem(MainClass.TeboRaw, "TeboRaw");
		GameRegistry.registerItem(MainClass.TeboCooked, "TeboCooked");
		GameRegistry.registerItem(MainClass.NogtailRaw, "NogtailRaw");
		GameRegistry.registerItem(MainClass.NogtailCooked, "NogtailCooked");
		GameRegistry.registerItem(MainClass.RamoraRaw, "RamoraRaw");
		GameRegistry.registerItem(MainClass.RamoraCooked, "RamoraCooked");
		GameRegistry.registerItem(MainClass.DPSWandClass, "DPSWandClass");
		GameRegistry.registerItem(MainClass.TankWandClass, "TankWandClass");
		GameRegistry.registerItem(MainClass.SupportWandClass, "SupportWandClass");
		GameRegistry.addRecipe(new ItemStack(MainClass.Gillyweed, 1), new Object[] { " O ", " X ", "   ", 'X', Items.wheat, 'O', Items.glass_bottle });
		GameRegistry.addRecipe(new ItemStack(MainClass.EveryFlavourBeans, 1), new Object[] { "XXX", "XOX", "XXX", 'X', Items.paper, 'O', Items.apple });
		GameRegistry.addRecipe(new ItemStack(MainClass.ChocolateFrog, 1), new Object[] { "XXX", "XOX", "XXX", 'X', Items.paper, 'O', Items.cake });
		GameRegistry.addRecipe(new ItemStack(MainClass.TimeTurner, 1), new Object[] { "   ", " x ", " O ", 'x', Items.gold_ingot, 'O', Items.clock });
		GameRegistry.addRecipe(new ItemStack(MainClass.Bat, 1), new Object[] { "   ", " O ", " x ", 'x', Items.stick, 'O', Blocks.planks });
		GameRegistry.addRecipe(new ItemStack(MainClass.Crystalball, 1), new Object[] { "   ", " x ", " O ", 'x', Blocks.glass, 'O', Blocks.obsidian });
		GameRegistry.addRecipe(new ItemStack(MainClass.MagicBook, 1), new Object[] { "xxx", "xOx", "xxx", 'x', Items.glowstone_dust, 'O', Items.book });
		GameRegistry.addRecipe(new ItemStack(MainClass.MonsterBook, 1), new Object[] { "xxx", "xOx", "xxx", 'x', Items.redstone, 'O', Items.book });
		GameRegistry.addRecipe(new ItemStack(MainClass.TheGoldenSnitch, 1), new Object[] { "x x", " o ", "   ", 'x', MainClass.SilverIngot, 'o', Items.gold_ingot });
		GameRegistry.addRecipe(new ItemStack(MainClass.Quaffle, 1), new Object[] { "xxx", "xOx", "xxx", 'x', Items.leather, 'O', Blocks.wool });
		GameRegistry.addRecipe(new ItemStack(MainClass.Bludger, 1), new Object[] { "xxx", "xOx", "xxx", 'x', Items.leather, 'O', Blocks.iron_block });
		GameRegistry.addRecipe(new ItemStack(MainClass.FordAnglia, 1), new Object[] { "xxx", "OOO", "xIx", 'x', Blocks.wool, 'O', Blocks.glass, 'I', Items.minecart });
		GameRegistry.addRecipe(new ItemStack(MainClass.Motercycle, 1), new Object[] { "  O", " x ", "O O", 'x', Items.minecart, 'O', Blocks.wool });
		GameRegistry.addRecipe(new ItemStack(MainClass.Motercycle2, 1), new Object[] { "   ", "   ", "Ox ", 'x', MainClass.Motercycle, 'O', Items.minecart });
		GameRegistry.addRecipe(new ItemStack(MainClass.Broomstick, 1), new Object[] { "x  ", " x ", "  o", 'x', Items.stick, 'o', Items.wheat });
		GameRegistry.addRecipe(new ItemStack(MainClass.Broomstick, 1), new Object[] { "  x", " x ", "o  ", 'x', Items.stick, 'o', Items.wheat });
		GameRegistry.addRecipe(new ItemStack(MainClass.Broomstick, 1), new Object[] { "o  ", " x ", "  x", 'x', Items.stick, 'o', Items.wheat });
		GameRegistry.addRecipe(new ItemStack(MainClass.Broomstick, 1), new Object[] { "  o", " x ", "x  ", 'x', Items.stick, 'o', Items.wheat });
		GameRegistry.addRecipe(new ItemStack(MainClass.MaraudersMap, 1), new Object[] { "xxx", "xxx", "xxx", 'x', Items.map, 'o', Items.wheat });
		GameRegistry.addRecipe(new ItemStack(MainClass.WerewolfForm, 1), new Object[] { "xxx", "xox", "xxx", 'x', Items.gold_ingot, 'o', Items.clock });
		GameRegistry.addRecipe(new ItemStack(MainClass.OakStick, 1), new Object[] { " ", "x", "x", 'x', new ItemStack(Blocks.log, 1, 0) });
		GameRegistry.addRecipe(new ItemStack(MainClass.BirchStick, 1), new Object[] { " ", "x", "x", 'x', new ItemStack(Blocks.log, 1, 2) });
		GameRegistry.addRecipe(new ItemStack(MainClass.WandCrafterIdle, 1),
				new Object[] { "  x", "ooo", "zcz", 'x', Items.blaze_rod, 'o', Blocks.carpet, 'z', Blocks.obsidian, 'c', Items.nether_star });
		GameRegistry.addRecipe(new ItemStack(MainClass.Cabinet, 1), new Object[] { "zzz", "ooo", "oco", 'o', Blocks.planks, 'c', Blocks.wooden_door, 'z', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.BoggartChestLocked, 1), new Object[] { "zzz", "zzz", "zcz", 'c', Blocks.chest, 'z', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.Penknife, 1), new Object[] { " l ", " O ", " x ", 'x', Items.stick, 'O', Items.iron_ingot, 'l', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.ItemStore, 1), new Object[] { "lll", "lOl", "lll", 'l', Items.leather, 'O', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.PensievePlane, 1), new Object[] { "O O", "lOl", " l ", 'l', Blocks.glass, 'O', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.Pensieve, 1), new Object[] { "   ", "lOl", "lll", 'l', Blocks.sandstone, 'O', MainClass.PensievePlane });
		GameRegistry.addRecipe(new ItemStack(MainClass.ButterBeer, 1), new Object[] { "OlO", "OlO", "OOO", 'O', Blocks.glass, 'l', Items.milk_bucket });
		GameRegistry.addRecipe(new ItemStack(MainClass.Hat, 1), new Object[] { " l ", "lll", "l l", 'l', Items.leather });
		GameRegistry.addRecipe(new ItemStack(MainClass.MirrorShard, 1), new Object[] { "   ", "   ", " l ", 'l', Blocks.glass_pane });
		GameRegistry.addRecipe(new ItemStack(MainClass.Key, 1), new Object[] { " O ", "lOl", " O ", 'l', Blocks.wool, 'O', Items.iron_ingot });
		GameRegistry.addRecipe(new ItemStack(MainClass.MasterKey, 1), new Object[] { " O ", "lOl", " O ", 'l', Blocks.lapis_block, 'O', Items.iron_ingot });
		GameRegistry.addRecipe(new ItemStack(MainClass.Remembrall, 1), new Object[] { "lll", "lOl", "lll", 'l', Blocks.glass, 'O', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.PutOuter, 1), new Object[] { " l ", " O ", " n ", 'l', Items.glowstone_dust, 'O', MainClass.MagicPower, 'n', Blocks.obsidian });
		GameRegistry.addRecipe(new ItemStack(MainClass.Mirror, 1), new Object[] { "nln", "nln", "nln", 'l', Blocks.glass_pane, 'n', Blocks.gold_block });
		GameRegistry.addRecipe(new ItemStack(MainClass.Hat, 1), new Object[] { "   ", "   ", " l ", 'l', Items.rotten_flesh });
		GameRegistry.addRecipe(new ItemStack(MainClass.TriCup, 1), new Object[] { "OmO", " l ", "lll", 'l', Items.iron_ingot, 'm', MainClass.MagicPower, 'O', Blocks.glass_pane });
		GameRegistry.addRecipe(new ItemStack(MainClass.GOF, 1), new Object[] { "lml", " l ", "lll", 'l', Blocks.sandstone, 'm', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.BlackMarbleBrick, 1), new Object[] { " ", " ", "l", 'l', MainClass.BlackMarble });
		GameRegistry.addRecipe(new ItemStack(MainClass.BlackMarbleBrick, 1), new Object[] { " ", "l", " ", 'l', MainClass.BlackMarble });
		GameRegistry.addRecipe(new ItemStack(MainClass.BlackMarbleBrick, 1), new Object[] { "l", " ", " ", 'l', MainClass.BlackMarble });
		GameRegistry.addRecipe(new ItemStack(MainClass.MarblePillar, 1), new Object[] { " ", " ", "l", 'l', MainClass.SmoothMarble });
		GameRegistry.addRecipe(new ItemStack(MainClass.MarblePillar, 1), new Object[] { " ", "l", " ", 'l', MainClass.SmoothMarble });
		GameRegistry.addRecipe(new ItemStack(MainClass.MarblePillar, 1), new Object[] { "l", " ", " ", 'l', MainClass.SmoothMarble });
		GameRegistry.addRecipe(new ItemStack(MainClass.Brick, 1), new Object[] { " ", " ", "l", 'l', Blocks.brick_block });
		GameRegistry.addRecipe(new ItemStack(MainClass.Brick, 1), new Object[] { " ", "l", " ", 'l', Blocks.brick_block });
		GameRegistry.addRecipe(new ItemStack(MainClass.Brick, 1), new Object[] { "l", " ", " ", 'l', Blocks.brick_block });
		GameRegistry.addRecipe(new ItemStack(MainClass.StoneSoldierBlock, 1), new Object[] { "l", "k", "j", 'l', Items.iron_helmet, 'k', MainClass.Brick, 'j', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.AurorHat, 1), new Object[] { " x ", "xyx", "x x", 'x', Items.leather, 'y', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.AurorChest, 1), new Object[] { "z z", "xyx", "xxx", 'x', Items.leather, 'y', MainClass.MagicPower, 'z', Items.iron_ingot });
		GameRegistry.addRecipe(new ItemStack(MainClass.AurorLegs, 1), new Object[] { "xyx", "xxx", "xxx", 'x', Items.leather, 'y', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.AurorShoes, 1), new Object[] { "y y", "x x", 'x', Items.leather, 'y', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.DeathEaterHat, 1), new Object[] { "xxx", "xzx", "xyx", 'x', Blocks.obsidian, 'y', MainClass.MagicPower, 'z', Items.iron_ingot });
		GameRegistry.addRecipe(new ItemStack(MainClass.DeathEaterChest, 1), new Object[] { "z z", "xyx", "xxx", 'x', Blocks.obsidian, 'y', MainClass.MagicPower, 'z', Items.iron_ingot });
		GameRegistry.addRecipe(new ItemStack(MainClass.DeathEaterLegs, 1), new Object[] { "xyx", "xxx", "xxx", 'x', Blocks.obsidian, 'y', MainClass.MagicPower });
		GameRegistry.addRecipe(new ItemStack(MainClass.DeathEaterShoes, 1), new Object[] { "y y", "x x", 'x', Blocks.obsidian, 'y', MainClass.MagicPower });
		GameRegistry.addSmelting(MainClass.TeboRaw, new ItemStack(MainClass.TeboCooked), 10.0f);
		GameRegistry.addSmelting(MainClass.SilverOre, new ItemStack(MainClass.SilverIngot), 20.0f);
		GameRegistry.addSmelting(MainClass.NogtailRaw, new ItemStack(MainClass.NogtailCooked), 9.0f);
		GameRegistry.addSmelting(MainClass.RamoraRaw, new ItemStack(MainClass.RamoraCooked), 9.0f);
		GameRegistry.addSmelting(MainClass.Marble, new ItemStack(MainClass.SmoothMarble), 3.0f);
		GameRegistry.addSmelting(MainClass.BlackMarble, new ItemStack(MainClass.SmoothBlackMarble), 3.0f);
		GameRegistry.registerWorldGenerator(this.eventWorldGen, 6);
		EntityRegistry.findGlobalUniqueEntityId();
		EntityRegistry.registerGlobalEntityID(EntityQuaffle.class, "Quaffle", EntityRegistry.findGlobalUniqueEntityId());


		MainClass.proxy.registerItemRenderers();
		MainClass.proxy.preInit();
		MainClass.proxy.renderStuff();
		MainClass.proxy.registerItemRenderers();
		EntityHandler.registerHorntail(EntityHorntail.class, "Horntail");
		EntityHandler.registerHorntail(EntityUkaranianIronbelly.class, "UkaranianIronbelly");
		MagicLeveling.calculateNeededExp();
		EntityHandler.registerBasilisk(EntityBasilisk.class, "Basilisk");
		EntityHandler.registerFluffy(EntityFluffy.class, "Fluffy");
		EntityHandler.registerWerewolf(EntityWerewolfMob.class, "Werewolf");
		EntityHandler.registerHippogriff(EntityHippogriff.class, "Hippogriff");
		EntityHandler.registerPhoenix(EntityPhoenix.class, "Phoenix");
		EntityHandler.registerDementor(EntityDementor.class, "Dementor");
		EntityHandler.registerBook(EntityBook.class, "Book");
		EntityHandler.registerSnake(EntitySnake.class, "Snake");
		EntityHandler.registerShield(EntityShield.class, "Shield");
		EntityHandler.registerPatronus(EntityPatronus.class, "Patronus");
		EntityHandler.registerBird(EntityBird.class, "Bird");
		EntityHandler.registerImperio(EntityImperioMob.class, "Imperio");
		EntityHandler.registerMonsterBook(EntityMonsterBook.class, "MonsterBook");
		EntityHandler.registerLevitate(EntityLevitate.class, "Levitate");
		EntityHandler.registerSnitch(EntityGoldenSnitch.class, "GoldenSnitch");
		EntityHandler.registerBludger(EntityBludger.class, "Bludger");
		EntityHandler.registerFord(EntityFordAnglia.class, "FordAnglia");
		EntityHandler.registerMotocycle(EntityMotorbike.class, "Motorbike");
		EntityHandler.registerMotocycle2(EntityMotorbike2.class, "Motorbike2");
		EntityHandler.registerBroom(EntityFlyingBroomstick.class, "FlyingBroomstick");
		EntityHandler.registerSpider(EntityAragog.class, "Aragog");
		EntityHandler.registerForm(EntityWerewolf.class, "WerewolfForm");
		EntityHandler.registerForm(EntityStagForm.class, "StagForm");
		EntityHandler.registerForm(EntityDogForm.class, "DogForm");
		EntityHandler.registerForm(EntityCatForm.class, "CatForm");
		EntityHandler.registerForm(EntityRatForm.class, "RatForm");
		EntityHandler.registerForm(EntityPhoenixForm.class, "PhoenixForm");
		EntityHandler.registerForm(EntityRavenForm.class, "RavenForm");
		EntityHandler.registerForm(EntitySnidgetForm.class, "SnidgetForm");
		EntityHandler.registerForm(EntityFalconForm.class, "FalconForm");
		EntityHandler.registerForm(EntityOwlForm.class, "OwlForm");
		EntityHandler.registerProjectile(ExpelliarmusProjectile.class, "ExpelliarmusProjectile");
		EntityHandler.registerProjectile(AvadakedavraProjectile.class, "AvadakedavraProjectile");
		EntityHandler.registerProjectile(PatronusProjectile.class, "PatronusProjectile");
		EntityHandler.registerNagini(EntityNagini.class, "Nagini");
		EntityHandler.registerSnitch(EntityKey.class, "Key");
		EntityHandler.registerSnitch(EntityMasterKey.class, "MasterKey");
		EntityHandler.registerGhost(EntityGhost.class, "Ghost");
		EntityHandler.registerFiendfyre(EntityFiendfyreDragon.class, "FiendfyreDragon");
		EntityHandler.registerProjectile(StupefyProjectile.class, "StupefyProjectile");
		EntityHandler.registerProjectile(ConfringoProjectile.class, "ConfringoProjectile");
		EntityHandler.registerProjectile(ReductoProjectile.class, "ReductoProjectile");
		EntityHandler.registerProjectile(CrucioProjectile.class, "CrucioProjectile");
		EntityHandler.registerProjectile(ImperioProjectile.class, "ImperioProjectile");
		EntityHandler.registerProjectile(AraniaExumaiProjectile.class, "AraniaExumaiProjectile");
		EntityHandler.registerProjectile(SectumsempraProjectile.class, "SectumsempraProjectile");
		EntityHandler.registerProjectile(LevicorpusProjectile.class, "LevicorpusProjectile");
		EntityHandler.registerProjectile(IncendioProjectile.class, "IncendioProjectile");
		EntityHandler.registerProjectile(StunProjectile.class, "StunProjectile");
		EntityHandler.registerProjectile(ConfundoProjectile.class, "ConfundoProjectile");
		EntityHandler.registerCabinet(EntityCabinet.class, "EntityCabinet");
		EntityHandler.registerCabinet(EntityCabinet2.class, "EntityCabinet2");
		EntityHandler.registerElf(EntityHouseElf.class, "EntityHouseElf");
		EntityHandler.registerBoggart(EntityBoggartDementor.class, "BoggartDementor");
		EntityHandler.registerProjectile(PatronusStrongProjectile.class, "PatronusStrongProjectile");
		EntityHandler.registerProjectile(ExpelliarmusStrongProjectile.class, "ExpelliarmusStrongProjectile");
		EntityHandler.registerProjectile(ConfringoStrongProjectile.class, "ConfringoStrongProjectile");
		EntityHandler.registerProjectile(ReductoStrongProjectile.class, "ReductoStrongProjectile");
		EntityHandler.registerProjectile(CrucioStrongProjectile.class, "CrucioStrongProjectile");
		EntityHandler.registerProjectile(LevicorpusStrongProjectile.class, "LevicorpusStrongProjectile");
		EntityHandler.registerProjectile(StunStrongProjectile.class, "StunStrongProjectile");
		EntityHandler.registerProjectile(ConfundoStrongProjectile.class, "ConfundStrongoProjectile");
		EntityHandler.registerProjectile(StupefyStrongProjectile.class, "StupefyStrongProjectile");
		EntityHandler.registerWingedHorse(EntityWingedHorse.class, "WingedHorse");
		EntityHandler.registerProjectile(SectumsempraStrongProjectile.class, "SectumsempraStrongProjectile");
		EntityHandler.registerUnicorn(EntityUnicorn.class, "Unicorn");
		EntityHandler.registerThestral(EntityThestral.class, "Thestral");
		EntityHandler.registerBillywig(EntityBillywig.class, "Billywig");
		EntityHandler.registerGriffin(EntityGriffin.class, "Griffin");
		EntityHandler.registerGrindylow(EntityGrindylow.class, "Grindylow");
		EntityHandler.registerHippocampus(EntityHippocampus.class, "Hippocampus");
		EntityHandler.registerPuffskein(EntityPuffskein.class, "Puffskein");
		EntityHandler.registerNogtail(EntityNogtail.class, "Nogtail");
		EntityHandler.registerRunespoor(EntityRunespoor.class, "Runespoor");
		EntityHandler.registerTroll(EntityTroll.class, "Troll");
		EntityHandler.registerRedCap(EntityRedCap.class, "RedCap");
		EntityHandler.registerBowtruckle(EntityBowtruckle.class, "Bowtruckle");
		EntityHandler.registerPixie(EntityPixie.class, "Pixie");
		EntityHandler.registerGoblin(EntityGoblin.class, "Goblin");
		EntityHandler.registerFairy(EntityFairy.class, "Fairy");
		EntityHandler.registerAugurey(EntityAugurey.class, "Augurey");
		EntityHandler.registerClabbert(EntityClabbert.class, "Clabbert");
		EntityHandler.registerBundimun(EntityBundimun.class, "Bundimun");
		EntityHandler.registerChizpurfle(EntityChizpurfle.class, "Chizpurfle");
		EntityHandler.registerMermaid(EntityMermaid.class, "Mermaid");
		EntityHandler.registerCentaur(EntityCentaur.class, "Centaur");
		EntityHandler.registerDugbog(EntityDugbog.class, "Dugbog");
		EntityHandler.registerGnome(EntityGnome.class, "Gnome");
		EntityHandler.registerTebo(EntityTebo.class, "Tebo");
		EntityHandler.registerRamora(EntityRamora.class, "Ramora");
		EntityHandler.registerMoke(EntityMoke.class, "Moke");
		EntityHandler.registerJobberknoll(EntityJobberknoll.class, "Jobberknoll");
		EntityHandler.registerSnidget(EntitySnidget.class, "Snidget");
		EntityHandler.registerDemiguise(EntityDemiguise.class, "Demiguise");
		EntityHandler.registerFireCrab(EntityFireCrab.class, "FireCrab");
		EntityHandler.registerFlobberworm(EntityFlobberworm.class, "Flobberworm");
		EntityHandler.registerFwooper(EntityFwooper.class, "Fwooper");
		EntityHandler.registerGhoul(EntityGhoul.class, "Ghoul");
		EntityHandler.registerGraphorn(EntityGraphorn.class, "Graphorn");
		EntityHandler.registerHorklump(EntityHorklump.class, "Horklump");
		EntityHandler.registerImp(EntityImp.class, "Imp");
		EntityHandler.registerJarvey(EntityJarvey.class, "Jarvey");
		EntityHandler.registerKelpie(EntityKelpie.class, "Kelpie");
		EntityHandler.registerKnarl(EntityKnarl.class, "Knarl");
		EntityHandler.registerKneazle(EntityKneazle.class, "Kneazle");
		EntityHandler.registerNundu(EntityNundu.class, "Nundu");
		EntityHandler.registerOccamy(EntityOccamy.class, "Occamy");
		EntityHandler.registerQuintaped(EntityQuintaped.class, "Quintaped");
		EntityHandler.registerReem(EntityReem.class, "Reem");
		EntityHandler.registerVeela(EntityVeela.class, "Veela");
		EntityHandler.registerLeprechaun(EntityLeprechaun.class, "Leprechaun");
		EntityHandler.registerStoneSoldier(EntityStoneSoldier.class, "StoneSoldier");

		GameRegistry.registerTileEntity(TileEntityWandCrafter.class, "TileEntityWandCrafter");
		GameRegistry.registerTileEntity(TileEntityStoneSoldierBlock.class, "TileEntityStoneSoldierBlock");
		GameRegistry.registerTileEntity(TileEntityPensieve.class, "TileEntityPensieve");
		GameRegistry.registerTileEntity(TileEntityBoggartChestLocked.class, "TileEntityBoggartChestLocked");
		GameRegistry.registerTileEntity(TileEntityBoggartChestOpen.class, "TileEntityBoggartChestOpen");
		GameRegistry.registerTileEntity(TileEntityTriCup.class, "TileEntityTriCup");
		GameRegistry.registerTileEntity(TileEntityEveryFlavourBeans.class, "TileEntityEveryFlavourBeans");
		GameRegistry.registerTileEntity(TileEntityHand.class, "TileEntityHand");
		GameRegistry.registerTileEntity(TileEntityGoldenEggOpen.class, "TileEntityGoldenEggOpen");
		GameRegistry.registerTileEntity(TileEntityGoldenEgg.class, "TileEntityGoldenEgg");
		GameRegistry.registerTileEntity(TileEntityDarkMarkClass.class, "TileEntityDarkMarkClass");
		GameRegistry.registerTileEntity(TileEntityLocket.class, "TileEntityLocket");
		GameRegistry.registerTileEntity(TileEntityPensievePlane.class, "TileEntityPensievePlane");
		GameRegistry.registerTileEntity(TileEntityHat.class, "TileEntityHat");
		GameRegistry.registerTileEntity(TileEntityCup.class, "TileEntityCup");
		GameRegistry.registerTileEntity(TileEntityDiadem.class, "TileEntityDiadem");
		GameRegistry.registerTileEntity(TileEntityDiary.class, "TileEntityDiary");
		GameRegistry.registerTileEntity(TileEntityRing.class, "TileEntityRing");
		GameRegistry.registerTileEntity(TileEntityCabinet.class, "TileEntityCabinet");
		GameRegistry.registerTileEntity(TileEntityCrystalball.class, "TileEntityCrystalball");
		GameRegistry.registerTileEntity(TileEntityMirror.class, "TileEntityMirror");
		GameRegistry.registerTileEntity(TileEntityGOF.class, "TileEntityGOF");

	}

	@Mod.EventHandler
	@SideOnly(Side.CLIENT)
	public void postInit(final FMLPostInitializationEvent event) {
		MinecraftForge.EVENT_BUS.register(new SpellGUI(Minecraft.getMinecraft()));
	}

	@Mod.EventHandler
	public void load(final FMLInitializationEvent event) {
		MinecraftForge.EVENT_BUS.register(new MagicEventHandler());
		FMLCommonHandler.instance().bus().register(new MagicEventHandler());
		NetworkRegistry.INSTANCE.registerGuiHandler(this, new GuiHandler());
	}

	public static boolean isServer() {
		return FMLCommonHandler.instance().getEffectiveSide() == Side.SERVER;
	}

}
